### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Openshift#8]
@Meir017 Would it be possible to provide some contact details for yourself? Do you have for example a twitter account?

If you could let me know the best email address to get you on as well, I will send an invite for you to join our Slack Team.

**Comment by Meir017** [comment]
email: meirblachman@gmail.com
twitter https://twitter.com/MeirBlachman

**Comment by gep13** [comment]
Perfect, thank you!
